### ISSUE TITLE
adjust Dockerfile

### ISSUE THREAD

**Issue by lpandath** [tugraz-rdm/damap-frontend#32]
**Description**
A clear and concise description of what you're missing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_If this issue requests multiple changes consider using checkboxes or lists._

**Comment by rekt-hard** [comment]
For reference: https://github.com/tugraz-rdm/damap-backend-tugraz/blob/108a7de2ed7e351a4561e7c03759fd84a5707fc8/Dockerfile#L8-L16
