### ISSUE TITLE
The tooltips starting with `help` are not resolved properly

### ISSUE THREAD

**Issue by rekt-hard** [tugraz-rdm/damap-frontend#33]
The tooltips starting with `help` are not resolved properly in our instance:
![image](https://github.com/tugraz-rdm/damap-frontend/assets/72449192/1e12dd66-1caf-4cd1-9b67-6a16bb33d271)

_Originally posted by @rekt-hard in https://github.com/tugraz-rdm/damap-frontend/pull/31#pullrequestreview-1996337246_

**Comment by lpandath** [comment]
@rekt-hard please add also this part here since its related. Thanks

  Localization in DE for DMP TUGraz
        Problem: German localization issues observed specific to DMP TUGraz.

**Comment by rekt-hard** [comment]
Also `info.ethical.humanParticipants.researchEthics.text`
